version: "3"

tasks:
  run:
    desc: Run all applications
    deps:
      - run:alerter
      - run:processor

  run:alerter:
    dir: alerter
    cmd: task run

  run:processor:
    dir: processor
    cmd: task run

  run:sensor:
    dir: processor
    cmd: task run

  run:broker:
    cmd: rumqtt -c config.toml


  build:
    cmd: cargo build --workspace
