BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "ipc-monitoring"
BBFILE_PATTERN_ipc-monitoring = "^${LAYERDIR}/"
BBFILE_PRIORITY_ipc-monitoring = "6"

LAYERDEPENDS_ipc-monitoring = "core"
LAYERSERIES_COMPAT_ipc-monitoring = "wrynose"
