CONF_VERSION = "2"

IMAGE_INSTALL:append = " ipc-monitoring"

DISTRO_FEATURES:append = " systemd usrmerge"
DISTRO_FEATURES:remove = "sysvinit"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = ""

# allow root login with no passwd
EXTRA_IMAGE_FEATURES += "allow-empty-password allow-root-login empty-root-password"
